# Generated by Django 2.2.6 on 2019-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.CharField(max_length=400)),
                ('picture', models.FileField(upload_to='')),
                ('difficulty', models.CharField(choices=[('Easy', '容易'), ('Medium', '中等'), ('Hard', '困难')], max_length=10)),
                ('prep_time', models.PositiveIntegerField()),
                ('prep_guide', models.TextField()),
            ],
        ),
    ]
